### ISSUE TITLE
Chown permission denied

### ISSUE THREAD

**Issue by courcelm** [vieux/docker-volume-sshfs#15]
I'm having the following issue when starting mysql container:

First I checked that the volume is ok by listing files

$ sudo docker run -it --rm -v pikwik_db:/data busybox ls /data
auto.cnf            ibdata1             piwik
ib_buffer_pool      ibtmp1              sys
ib_logfile0         mysql
ib_logfile1         performance_schema

Then I try to use the same volume with mysql container:

$ sudo docker run -it --rm -v pikwik_db:/var/lib/mysql mysql ls /var/lib/mysql
docker: Error response from daemon: chown /var/lib/docker/plugins/372d1d7033a77d00855281929c54eda68d63acc7258253f3e7a5966b4dec161a/rootfs/mnt/volumes/1f57d00c7a2b03eddb42d0d9907d6998: permission denied.
See 'docker run --help'.

**Comment by chrsch** [comment]
I have the same problem. Listing files work but using the volume in a container produces above error.

**Comment by cybertk** [comment]
Same issue here, while WORKDIR is same as mount path.

**Comment by vieux** [comment]
I believe this was fixed by https://github.com/vieux/docker-volume-sshfs/pull/18

**Comment by matthew-mcallister** [comment]
@vieux This doesn't appear to fix it, at least not for me: https://i.fluffy.cc/75rnP25jdpV1Knf1JXmMTw1Fpff6r4jQ.html

**Comment by zener79** [comment]
same problem here running on swarm mode

**Comment by kushtrimjunuzi** [comment]
try this workaround, it did worked for me

sudo bindfs --chown-ignore --chgrp-ignore /sshfs-mountpoint /destination
